services:
  noetic_desktop:
    build:
      context: .
      dockerfile: Dockerfile.ros
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - ./ros_ws:/ros_ws
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      ROS_MASTER_URI: http://localhost:11311
      ROS_HOSTNAME: localhost
    network_mode: "host"
    tty: true
    stdin_open: true
    ulimits:
      nofile: 65535 # Increase the limit for open files
      nproc: 4096   # Limit the number of processes
    extra_hosts:
      - "localhost:127.0.0.1"

