// Generated by gencpp from file ros1_msgs_srvs/Int8.msg
// DO NOT EDIT!


#ifndef ROS1_MSGS_SRVS_MESSAGE_INT8_H
#define ROS1_MSGS_SRVS_MESSAGE_INT8_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros1_msgs_srvs
{
template <class ContainerAllocator>
struct Int8_
{
  typedef Int8_<ContainerAllocator> Type;

  Int8_()
    : data(0)  {
    }
  Int8_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros1_msgs_srvs::Int8_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros1_msgs_srvs::Int8_<ContainerAllocator> const> ConstPtr;

}; // struct Int8_

typedef ::ros1_msgs_srvs::Int8_<std::allocator<void> > Int8;

typedef boost::shared_ptr< ::ros1_msgs_srvs::Int8 > Int8Ptr;
typedef boost::shared_ptr< ::ros1_msgs_srvs::Int8 const> Int8ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros1_msgs_srvs::Int8_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros1_msgs_srvs::Int8_<ContainerAllocator1> & lhs, const ::ros1_msgs_srvs::Int8_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros1_msgs_srvs::Int8_<ContainerAllocator1> & lhs, const ::ros1_msgs_srvs::Int8_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros1_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros1_msgs_srvs::Int8_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros1_msgs_srvs::Int8_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros1_msgs_srvs::Int8_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::ros1_msgs_srvs::Int8_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros1_msgs_srvs/Int8";
  }

  static const char* value(const ::ros1_msgs_srvs::Int8_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data\n"
;
  }

  static const char* value(const ::ros1_msgs_srvs::Int8_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Int8_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros1_msgs_srvs::Int8_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros1_msgs_srvs::Int8_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS1_MSGS_SRVS_MESSAGE_INT8_H
