#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'navigation','console_scripts','mapping_aware'
__requires__ = 'navigation'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('navigation', 'console_scripts', 'mapping_aware')()
    )
