version: "3.9"
services:
  ros1:
    build:
      context: .
      dockerfile: ros1.Dockerfile
    volumes:
      - ./src:/workspace/src
    networks:
      - mynet
  ros2:
    build:
      context: .
      dockerfile: ros2.Dockerfile
    volumes:
      - ./src:/workspace/src
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
