#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'joy-to-motion','console_scripts','joy_to_motion'
__requires__ = 'joy-to-motion'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('joy-to-motion', 'console_scripts', 'joy_to_motion')()
    )
