services:
  dev-environment:
    build: .
    runtime: nvidia
    network_mode: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # Mount Neovim configuration
      - ./config/nvim:/root/.config/nvim
      # Mount workspace for persistence
      - ~/Main:/workspace
      # Mount Zsh configuration
      - ./config/zshrc:/root/.zshrc
      # Mount Zsh configuration
      - ./config/p10k.zsh:/root/.p10k.zsh
      # Mount X11 socket for GUI access
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Mount .Xauthority for clipboard access
      - $HOME/.Xauthority:/root/.Xauthority:ro
      # Mount USB devices
      - /dev:/dev
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 15g
    command: zsh 

