services:
  ros_mindcloud_noetic:
    image: ros_noetic:latest
    build:
      context: .
      dockerfile: Dockerfile.ros
    volumes:
      - ./config/nvim:/root/.config/nvim
      - ./config/zshrc:/root/.zshrc
      - ./config/p10k.zsh:/root/.p10k.zsh
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - ./ros_ws:/ros_ws
      - /dev:/dev
      - ./start_ros.sh:/start_ros.sh
    privileged: true
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      ROS_MASTER_URI: http://localhost:11311
      ROS_HOSTNAME: localhost
    network_mode: "host"
    ulimits:
      nofile: 65535 # Increase the limit for open files
      nproc: 4096   # Limit the number of processes
    extra_hosts:
      - "localhost:127.0.0.1"
    entrypoint: ["/start_ros.sh"]
